"""empty message

Revision ID: 36f2cb49d826
Revises: b3383c14108b
Create Date: 2018-10-13 20:04:27.575277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f2cb49d826'
down_revision = 'b3383c14108b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entityflag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_flag_association',
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_flag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_flag_id'], ['entityflag.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_flag_association')
    op.drop_table('entityflag')
    # ### end Alembic commands ###
