"""empty message

Revision ID: 3a0771d74b59
Revises: fc828cd52f16
Create Date: 2018-11-23 18:31:21.530516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a0771d74b59'
down_revision = 'fc828cd52f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'schedule', 'site', ['site_id'], ['id'])
    op.add_column('site', sa.Column('spider_name', sa.String(length=50), nullable=True))
    op.execute("UPDATE site set spider_name='pbc' where site.base_url='http://oris.co.palm-beach.fl.us'")
    op.alter_column('site', 'spider_name', existing_type=sa.String(length=50), nullable=False)
    op.alter_column('site', 'last_scrape_datetime',
               existing_type=mysql.DATETIME(),
               nullable=False,
                server_default='1000-01-01')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site', 'last_scrape_datetime',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('site', 'spider_name')
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.drop_column('schedule', 'site_id')
    # ### end Alembic commands ###
