"""add info columns

Revision ID: 88797a888cae
Revises: 14cfe734c6c1
Create Date: 2018-09-17 14:08:31.776428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88797a888cae'
down_revision = '14cfe734c6c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('message', sa.VARCHAR(length=1000), nullable=True))
    op.add_column('document', sa.Column('name', sa.String(length=200), nullable=True))
    op.alter_column('sitescrapelogdetails', 'message',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sitescrapelogdetails', 'message',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
    op.drop_column('document', 'name')
    op.drop_column('document', 'message')
    # ### end Alembic commands ###
