"""entity_blcklist

Revision ID: a3da871bda7c
Revises: f7ecc6f60ff1
Create Date: 2018-12-22 11:58:00.775572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3da871bda7c'
down_revision = 'f7ecc6f60ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('black_listed', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity', 'black_listed')
    op.create_table('my_work_document_etl',
    sa.Column('defendant_name', mysql.VARCHAR(charset='utf8', length=1500), nullable=True),
    sa.Column('plantiff_name', mysql.VARCHAR(charset='utf8', length=1500), nullable=True),
    sa.Column('jud_doc_id', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('deed_doc_id', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
