"""star schema

Revision ID: b3383c14108b
Revises: c63c5a9f154a
Create Date: 2018-09-27 19:53:53.775122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3383c14108b'
down_revision = 'c63c5a9f154a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_name', 'entity', ['name'], unique=False, mysql_length=100)
    op.create_table('documentfact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('cfn', table_name='document')
    op.drop_index('pary2', table_name='document')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('pary2', 'document', ['party2'], unique=False)
    op.create_index('cfn', 'document', ['cfn'], unique=True)
    op.drop_table('documentfact')
    op.drop_index('idx_name', table_name='entity')
    op.drop_table('entity')
    # ### end Alembic commands ###
