"""empty message

Revision ID: d826484d85e8
Revises: 
Create Date: 2018-09-13 20:47:05.059827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd826484d85e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authtype',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table('documentflag',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('description', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id'))

    doctype = op.create_table('sitedoctype',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('description', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id'))

    op.bulk_insert(
        doctype,
       [{
           'name': 'D',
           'description': 'Deed'
       },
        {
            'name': 'JUD C',
            'description': 'Certified Judgment'
       }])

    site = op.create_table('site',
                           sa.Column('id', sa.Integer(), nullable=False),
                           sa.Column('base_url', sa.String(length=200), nullable=True),
                           sa.Column('last_scrape_datetime', sa.DateTime(), nullable=True),
                           sa.Column('creds', sa.JSON(), nullable=True),
                           sa.Column('auth_type_id', sa.Integer(), nullable=True),
                           sa.ForeignKeyConstraint(['auth_type_id'], ['authtype.id'], ),
                           sa.PrimaryKeyConstraint('id'))
    op.bulk_insert(
        site,
        [{'base_url': 'http://oris.co.palm-beach.fl.us'}]
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book', sa.String(length=100), nullable=True),
    sa.Column('book_type', sa.String(length=50), nullable=True),
    sa.Column('cfn', sa.String(length=250), nullable=True),
    sa.Column('consideration', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('cross_name', sa.VARCHAR(length=500), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('image_uri', sa.VARCHAR(length=800), nullable=True),
    sa.Column('legal', sa.String(length=200), nullable=True),
    sa.Column('page', sa.String(length=50), nullable=True),
    sa.Column('party1', sa.VARCHAR(length=500), nullable=True),
    sa.Column('party2', sa.VARCHAR(length=500), nullable=True),
    sa.Column('doctype_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctype_id'], ['sitedoctype.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sitedoctype_association',
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('doctype_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctype_id'], ['sitedoctype.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], )
    )
    op.create_table('documentflag_association',
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('documentflag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['documentflag_id'], ['documentflag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentflag_association')
    op.drop_table('sitedoctype_association')
    op.drop_table('document')
    op.drop_table('site')
    op.drop_table('sitedoctype')
    op.drop_table('documentflag')
    op.drop_table('authtype')
    # ### end Alembic commands ###
