"""fix info columns

Revision ID: ebb216d10e39
Revises: 88797a888cae
Create Date: 2018-09-17 14:58:15.658883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ebb216d10e39'
down_revision = '88797a888cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('info', sa.VARCHAR(length=1000), nullable=True))
    op.drop_column('document', 'message')
    op.add_column('sitescrapelogdetails', sa.Column('info', sa.VARCHAR(length=1000), nullable=True))
    op.alter_column('sitescrapelogdetails', 'message',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sitescrapelogdetails', 'message',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
    op.drop_column('sitescrapelogdetails', 'info')
    op.add_column('document', sa.Column('message', mysql.VARCHAR(length=1000), nullable=True))
    op.drop_column('document', 'info')
    # ### end Alembic commands ###
