"""empty message

Revision ID: f7ecc6f60ff1
Revises: 3a0771d74b59
Create Date: 2018-11-24 14:16:53.580960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ecc6f60ff1'
down_revision = '3a0771d74b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('last_poll_datetime', sa.DateTime(), nullable=False, server_default='1000-01-01'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'last_poll_datetime')
    # ### end Alembic commands ###
